name: dotnet-build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./github4women/github4women.csproj
      
    - name: Build
      run: dotnet build ./github4women/github4women.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test ./github4women/github4women.csproj --no-build --verbosity normal
      
    - name: Custom script
      run: |
        echo "Build completed at $(date)" >> build.log
        cat build.log
